# Generated by Django 4.2.16 on 2024-09-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walldetaileddata",
            options={
                "verbose_name": "双皮剪力墙深化设计",
                "verbose_name_plural": "双皮剪力墙深化设计",
            },
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="bottom_gap_height",
            field=models.IntegerField(null=True, verbose_name="底部间隙 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="cast_inserts_bottom_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="底部数量 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="cast_inserts_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="???预埋件设计方式",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="cast_inserts_left_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="左部数量 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="cast_inserts_right_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="右部数量 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="cast_inserts_top_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="顶部数量 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="circle_hole_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="circle_hole_horizontal",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口中心点水平定位 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="circle_hole_vertical",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口中心点竖向定位 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="diagonal_rebar_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架腹筋直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="diagonal_rebar_spacing",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架腹筋间距 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="distributed_rebar",
            field=models.IntegerField(
                choices=[(1, "桁架筋作为分布筋"), (0, "桁架筋不作为分布筋")],
                default=1,
                verbose_name="桁架筋是否作为分布筋",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="exterior_thickness",
            field=models.IntegerField(null=True, verbose_name="外墙厚度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="height",
            field=models.IntegerField(null=True, verbose_name="剪力墙高度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="horizontal_rebar_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="水平钢筋直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="horizontal_rebar_ratio",
            field=models.FloatField(
                blank=True, null=True, verbose_name="水平钢筋配筋率"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="horizontal_rebar_spacing",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="水平钢筋间距 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="interior_thickness",
            field=models.IntegerField(null=True, verbose_name="内墙厚度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="left_gap_length",
            field=models.IntegerField(null=True, verbose_name="左间隙长度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="length",
            field=models.IntegerField(null=True, verbose_name="剪力墙长度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="lifting_inserts_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="吊装预埋件设计方式",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="lifting_inserts_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="吊装预埋件直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="lifting_inserts_position_x1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="左吊装预埋件距左边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="lifting_inserts_position_x2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="右吊装预埋件距右边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="lifting_rebar",
            field=models.IntegerField(
                choices=[(1, "桁架筋作为吊装筋"), (0, "桁架筋不作为吊装筋")],
                default=1,
                verbose_name="桁架筋是否作为吊装筋",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="other_inserts",
            field=models.IntegerField(
                choices=[(1, "是"), (0, "否")],
                default=0,
                verbose_name="是否有其他预埋件",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="other_inserts_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="其他预埋件数量"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="other_inserts_parameters",
            field=models.TextField(
                blank=True,
                help_text="以[]列表的形式呈现",
                null=True,
                verbose_name="其他预埋件的直径尺寸列表",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="other_inserts_positions",
            field=models.TextField(
                blank=True,
                help_text="以[ [ ] ]的形式呈现",
                null=True,
                verbose_name="其他预埋件距离墙左方、下方的距离",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="rebar_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="钢筋设计方式",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="rectangle_hole_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口高度 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="rectangle_hole_horizontal",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口中心点水平定位 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="rectangle_hole_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口长度 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="rectangle_hole_vertical",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="洞口中心点竖向定位 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="right_gap_length",
            field=models.IntegerField(null=True, verbose_name="右间隙长度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="shear_wall_type",
            field=models.IntegerField(
                choices=[(0, "外墙"), (1, "内墙")], default=0, verbose_name="剪力墙类型"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_design_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="支撑预埋件设计方式",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_hole_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="支撑预埋件孔洞大小 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_position_x1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="距左边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_position_x2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="距右边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_position_y1",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="距下边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="support_inserts_position_y2",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="距上边界位置 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="thickness",
            field=models.IntegerField(null=True, verbose_name="剪力墙厚度 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="top_gap_height",
            field=models.IntegerField(null=True, verbose_name="顶部间隙 (mm)"),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_bottom_rebar_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架底部钢筋直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架高度 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_number",
            field=models.IntegerField(
                blank=True, default=2, null=True, verbose_name="桁架数量"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_rebar_mode",
            field=models.IntegerField(
                choices=[(0, "自动"), (1, "手动")],
                default=0,
                verbose_name="桁架钢筋设计方式",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_top_rebar_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架上部钢筋直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="truss_width",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="桁架宽度 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="trussing_rebar_name",
            field=models.CharField(
                choices=[
                    ["HPB300", "HPB300"],
                    ["HRB335", "HRB335"],
                    ["HRBF335", "HRBF335"],
                    ["HRB400", "HRB400"],
                    ["HRBF400", "HRBF400"],
                    ["RRB400", "RRB400"],
                    ["HRB500", "HRB500"],
                    ["HRBF500", "HRBF500"],
                ],
                default="HPB300",
                max_length=32,
                verbose_name="桁架钢筋等级",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="vertical_rebar_diameter",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="竖向钢筋直径 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="vertical_rebar_ratio",
            field=models.FloatField(
                blank=True, null=True, verbose_name="竖向钢筋配筋率"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="vertical_rebar_spacing",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="竖向钢筋间距 (mm)"
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="wall_hole",
            field=models.IntegerField(
                choices=[(1, "有洞口"), (0, "没有洞口")],
                default=1,
                verbose_name="剪力墙洞口",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="wall_hole_type",
            field=models.IntegerField(
                choices=[(1, "矩形洞口"), (0, "圆形洞口")],
                default=1,
                verbose_name="剪力墙洞口类型",
            ),
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="wall_length_type",
            field=models.IntegerField(
                choices=[(1, "内外墙板等长"), (0, "内墙短")],
                default=1,
                verbose_name="剪力墙长度类型",
            ),
        ),
        migrations.CreateModel(
            name="WallDetailedResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interior_height",
                    models.FloatField(null=True, verbose_name="内墙高度 (mm)"),
                ),
                (
                    "exterior_height",
                    models.FloatField(null=True, verbose_name="外墙高度 (mm)"),
                ),
                (
                    "left_gap_length",
                    models.FloatField(null=True, verbose_name="左边间隙 (mm)"),
                ),
                (
                    "right_gap_length",
                    models.FloatField(null=True, verbose_name="右边间隙 (mm)"),
                ),
                (
                    "interior_length",
                    models.FloatField(null=True, verbose_name="内墙长度 (mm)"),
                ),
                (
                    "exterior_length",
                    models.FloatField(null=True, verbose_name="外墙长度 (mm)"),
                ),
                ("volume", models.FloatField(null=True, verbose_name="体积")),
                ("area", models.FloatField(null=True, verbose_name="面积")),
                ("weight", models.FloatField(null=True, verbose_name="重量")),
                (
                    "horizontal_rebars",
                    models.TextField(blank=True, null=True, verbose_name="水平钢筋"),
                ),
                (
                    "vertical_rebars",
                    models.TextField(blank=True, null=True, verbose_name="竖向钢筋"),
                ),
                (
                    "wall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="design.walldetaileddata",
                        verbose_name="关联参数",
                    ),
                ),
            ],
            options={
                "verbose_name": "双皮剪力墙深化设计结果",
                "verbose_name_plural": "双皮剪力墙深化设计结果",
            },
        ),
    ]
