# Generated by Django 4.2.16 on 2024-09-24 11:06

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0002_alter_walldetaileddata_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walldetaileddata",
            name="remark_name",
            field=models.CharField(
                default=design.models.get_default_remark_name,
                max_length=64,
                null=True,
                verbose_name="参数编号",
            ),
        ),
        migrations.AlterField(
            model_name="walldetaileddata",
            name="other_inserts_parameters",
            field=models.TextField(
                blank=True,
                help_text="以[ ]列表的形式呈现",
                null=True,
                verbose_name="其他预埋件的直径尺寸列表",
            ),
        ),
    ]
