# Generated by Django 4.2.16 on 2024-09-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0004_alter_walldetaileddata_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walldetaileddata",
            name="concrete_grade",
            field=models.IntegerField(
                choices=[
                    [30, "C30"],
                    [35, "C35"],
                    [40, "C40"],
                    [45, "C45"],
                    [50, "C50"],
                    [60, "C60"],
                ],
                default=30,
                verbose_name="混凝土等级",
            ),
        ),
    ]
