# Generated by Django 4.2.16 on 2024-09-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0005_alter_walldetaileddata_concrete_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailDataCopyChangeWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField(verbose_name="design parameter")),
            ],
            options={
                "verbose_name": "深化设计-参数修改",
                "verbose_name_plural": "深化设计-参数修改",
            },
        ),
        migrations.AddField(
            model_name="walldetaileddata",
            name="pub_date",
            field=models.DateTimeField(null=True, verbose_name="发布时间"),
        ),
    ]
