# Generated by Django 4.2.16 on 2024-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0006_detaildatacopychangewrite_walldetaileddata_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walldetaileddata",
            name="other_inserts_parameters",
            field=models.TextField(
                blank=True,
                help_text="以逗号隔开",
                null=True,
                verbose_name="其他预埋件的直径尺寸列表",
            ),
        ),
        migrations.AlterField(
            model_name="walldetaileddata",
            name="other_inserts_positions",
            field=models.TextField(
                blank=True,
                help_text="以[ ]的形式呈现",
                null=True,
                verbose_name="其他预埋件距离墙左方、下方的距离",
            ),
        ),
    ]
