# Generated by Django 4.2.16 on 2024-09-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0007_alter_walldetaileddata_other_inserts_parameters_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="walldetaileddata",
            old_name="horizontal_rebar_ratio",
            new_name="horizontal_rebars_ratio",
        ),
        migrations.RenameField(
            model_name="walldetaileddata",
            old_name="vertical_rebar_ratio",
            new_name="vertical_rebars_ratio",
        ),
    ]
